/* Generated By:JJTree: Do not edit this line. ASTArrayDimsAndInits.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTArrayDimsAndInits extends SimpleNode {
  public ASTArrayDimsAndInits(int id) {
    super(id);
  }

  public ASTArrayDimsAndInits(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f1816cb8d4c4bdd704887024c57a5efa (do not edit this line) */
