/* Generated By:JJTree: Do not edit this line. ASTAndExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTAndExp extends SimpleNode {
  public ASTAndExp(int id) {
    super(id);
  }

  public ASTAndExp(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=688205d0f3f4b6831ba146ca769a7576 (do not edit this line) */
