/* Generated By:JJTree: Do not edit this line. ASTArguments.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTArguments extends SimpleNode {
  public ASTArguments(int id) {
    super(id);
  }

  public ASTArguments(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f854e9c82c4d351b3c3cb08fb8dbeaf6 (do not edit this line) */
