/* Generated By:JJTree: Do not edit this line. ASTAssignExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTAssignExp extends SimpleNode {
  public ASTAssignExp(int id) {
    super(id);
  }

  public ASTAssignExp(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6b73e4c7c132fa29ace577545f2345ab (do not edit this line) */
