/* Generated By:JJTree: Do not edit this line. ASTArrayType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTArrayType extends SimpleNode {
  public ASTArrayType(int id) {
    super(id);
  }

  public ASTArrayType(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=adae020b98fce6aa32f75d96e9e6fda2 (do not edit this line) */
