/* Generated By:JJTree: Do not edit this line. ASTAddExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTAddExp extends SimpleNode {
  public ASTAddExp(int id) {
    super(id);
  }

  public ASTAddExp(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dfd6e5bfc3f13890b81e7129e8a90290 (do not edit this line) */
