/* Generated By:JJTree: Do not edit this line. ASTBlockStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTBlockStatement extends SimpleNode {
  public ASTBlockStatement(int id) {
    super(id);
  }

  public ASTBlockStatement(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=09c2408d74d4264a42f0947008db3373 (do not edit this line) */
