/* Generated By:JJTree: Do not edit this line. ASTConstructorDecl.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTConstructorDecl extends SimpleNode {
  public ASTConstructorDecl(int id) {
    super(id);
  }

  public ASTConstructorDecl(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4eebfc9546dcae5f7d39452796c393c9 (do not edit this line) */
