/* Generated By:JJTree: Do not edit this line. ASTClassBodyDecl.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTClassBodyDecl extends SimpleNode {
  public ASTClassBodyDecl(int id) {
    super(id);
  }

  public ASTClassBodyDecl(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02451a49ba74b9b7d0942b80b486e6f4 (do not edit this line) */
