/* Generated By:JJTree: Do not edit this line. ASTCastExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTCastExpression extends SimpleNode {
  public ASTCastExpression(int id) {
    super(id);
  }

  public ASTCastExpression(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3da564135fbb4befb6c3831afe85e789 (do not edit this line) */
