/* Generated By:JJTree: Do not edit this line. ASTCastLookahead.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTCastLookahead extends SimpleNode {
  public ASTCastLookahead(int id) {
    super(id);
  }

  public ASTCastLookahead(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0b2d58de6697cb857edc16296f2ba557 (do not edit this line) */
