/* Generated By:JJTree: Do not edit this line. ASTDeclarator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTDeclarator extends SimpleNode {
  public ASTDeclarator(int id) {
    super(id);
  }

  public ASTDeclarator(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5e6f50f8f81e77139ab83ef3677ad788 (do not edit this line) */
