/* Generated By:JJTree: Do not edit this line. ASTExpressionStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTExpressionStatement extends SimpleNode {
  public ASTExpressionStatement(int id) {
    super(id);
  }

  public ASTExpressionStatement(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b11525e27b5cdfeddea93745a0d8a01 (do not edit this line) */
