/* Generated By:JJTree: Do not edit this line. ASTExpName.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTExpName extends SimpleNode {
  public ASTExpName(int id) {
    super(id);
  }

  public ASTExpName(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=847c216082b6f955320137dcf808b52a (do not edit this line) */
