/* Generated By:JJTree: Do not edit this line. ASTEqualityExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTEqualityExp extends SimpleNode {
  public ASTEqualityExp(int id) {
    super(id);
  }

  public ASTEqualityExp(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=39687bcce2a84c62f52dd6bae3d8116e (do not edit this line) */
