/* Generated By:JJTree: Do not edit this line. ASTEmptyStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTEmptyStatement extends SimpleNode {
  public ASTEmptyStatement(int id) {
    super(id);
  }

  public ASTEmptyStatement(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8056631a5ba16ea73fcddc160c6c691b (do not edit this line) */
