/* Generated By:JJTree: Do not edit this line. ASTExplicitConstructorInvocation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTExplicitConstructorInvocation extends SimpleNode {
  public ASTExplicitConstructorInvocation(int id) {
    super(id);
  }

  public ASTExplicitConstructorInvocation(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd7e62a0e3c2ff4f9a6333e1f40dd079 (do not edit this line) */
