/* Generated By:JJTree: Do not edit this line. ASTForInit.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTForInit extends SimpleNode {
  public ASTForInit(int id) {
    super(id);
  }

  public ASTForInit(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6d1c4b73a1403a00ae21716ce011146d (do not edit this line) */
