/* Generated By:JJTree: Do not edit this line. ASTFieldAccess.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTFieldAccess extends SimpleNode {
  public ASTFieldAccess(int id) {
    super(id);
  }

  public ASTFieldAccess(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=66b7685bcc889085bea3f02840bbbfce (do not edit this line) */
