/* Generated By:JJTree: Do not edit this line. ASTForStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTForStatement extends SimpleNode {
  public ASTForStatement(int id) {
    super(id);
  }

  public ASTForStatement(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a28fbf2b3499df059ea10e90fdb55f51 (do not edit this line) */
