/* Generated By:JJTree: Do not edit this line. ASTForeachStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTForeachStatement extends SimpleNode {
  public ASTForeachStatement(int id) {
    super(id);
  }

  public ASTForeachStatement(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=95d49d49ff635f3abd3b0197d2feb9d6 (do not edit this line) */
