/* Generated By:JJTree: Do not edit this line. ASTForUpdate.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTForUpdate extends SimpleNode {
  public ASTForUpdate(int id) {
    super(id);
  }

  public ASTForUpdate(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b436e33fd95d98ad7991c399d4caf0c4 (do not edit this line) */
