/* Generated By:JJTree: Do not edit this line. ASTFieldDecl.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTFieldDecl extends SimpleNode {
  public ASTFieldDecl(int id) {
    super(id);
  }

  public ASTFieldDecl(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a908f2cdfc38b6cc5eae846eedb8b6f7 (do not edit this line) */
