/* Generated By:JJTree: Do not edit this line. ASTInitializerExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTInitializerExp extends SimpleNode {
  public ASTInitializerExp(int id) {
    super(id);
  }

  public ASTInitializerExp(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2e9c46c1baaac6b12c8dce3338359691 (do not edit this line) */
