/* Generated By:JJTree: Do not edit this line. ASTInstanceOfExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTInstanceOfExp extends SimpleNode {
  public ASTInstanceOfExp(int id) {
    super(id);
  }

  public ASTInstanceOfExp(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4a681900f7518285dc0e22e128effa4 (do not edit this line) */
