/* Generated By:JJTree: Do not edit this line. ASTLocalVarDecl.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTLocalVarDecl extends SimpleNode {
  public ASTLocalVarDecl(int id) {
    super(id);
  }

  public ASTLocalVarDecl(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67d33e00042447cb3236d2f4deab451d (do not edit this line) */
