/* Generated By:JJTree: Do not edit this line. ASTModifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTModifier extends SimpleNamedNode {
  public ASTModifier(int id) {
    super(id);
  }

  public ASTModifier(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7cda49e80cfc639b3a3e262a21c243a1 (do not edit this line) */
