/* Generated By:JJTree: Do not edit this line. ASTModifierStatic.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTModifierStatic extends SimpleNode {
  public ASTModifierStatic(int id) {
    super(id);
  }

  public ASTModifierStatic(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=520739484dec581cf6c8800984091ec2 (do not edit this line) */
