/* Generated By:JJTree: Do not edit this line. ASTMultiExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTMultiExp extends SimpleNode {
  public ASTMultiExp(int id) {
    super(id);
  }

  public ASTMultiExp(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e687655701870bb2714df0afb6d52300 (do not edit this line) */
