/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTMethodDeclarator extends SimpleNode {
  public ASTMethodDeclarator(int id) {
    super(id);
  }

  public ASTMethodDeclarator(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f8fc5581be239d8a0d1f9b3b58e4a7a9 (do not edit this line) */
