/* Generated By:JJTree: Do not edit this line. ASTNotExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTNotExpression extends SimpleNode {
  public ASTNotExpression(int id) {
    super(id);
  }

  public ASTNotExpression(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=149d294a86ec36082b7c4eeacc9acde7 (do not edit this line) */
