/* Generated By:JJTree: Do not edit this line. ASTName.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTName extends SimpleNamedNode {
	
  public ASTName(int id) {
    super(id);
  }

  public ASTName(Scanner p, int id) {
    super(p, id);
  }
  
}
/* JavaCC - OriginalChecksum=044b0c893bb685b03bde71f0b3a844a5 (do not edit this line) */
