/* Generated By:JJTree: Do not edit this line. ASTOrExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTOrExp extends SimpleNode {
  public ASTOrExp(int id) {
    super(id);
  }

  public ASTOrExp(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6c586220c8ce86179cbd380a5186a740 (do not edit this line) */
