/* Generated By:JJTree: Do not edit this line. ASTPrimary.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTPrimary extends SimpleNode {
  public ASTPrimary(int id) {
    super(id);
  }

  public ASTPrimary(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3257bc08ad352d31944e27e93268358 (do not edit this line) */
