/* Generated By:JJTree: Do not edit this line. ASTPrimitiveType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTPrimitiveType extends SimpleNode {
  public ASTPrimitiveType(int id) {
    super(id);
  }

  public ASTPrimitiveType(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=35f09a39ef7cba9d6ef794fb9e471680 (do not edit this line) */
