/* Generated By:JJTree: Do not edit this line. ASTRelationalExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTRelationalExp extends SimpleNode {
  public ASTRelationalExp(int id) {
    super(id);
  }

  public ASTRelationalExp(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9281bbd410e1f0c54a65d024f83377e9 (do not edit this line) */
