/* Generated By:JJTree: Do not edit this line. ASTResultType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTResultType extends SimpleNamedNode {
  public ASTResultType(int id) {
    super(id);
  }

  public ASTResultType(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14424dbf4afa8d6b9f4c977352e8e7ef (do not edit this line) */
