/* Generated By:JJTree: Do not edit this line. ASTStatementExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTStatementExpression extends SimpleNode {
  public ASTStatementExpression(int id) {
    super(id);
  }

  public ASTStatementExpression(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3364c4dced1981bad5f9eaa73c4cca6c (do not edit this line) */
