/* Generated By:JJTree: Do not edit this line. ASTTypeDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTTypeDeclaration extends SimpleNode {
  public ASTTypeDeclaration(int id) {
    super(id);
  }

  public ASTTypeDeclaration(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d28bf4627f68c2425085148c90006f18 (do not edit this line) */
