/* Generated By:JJTree: Do not edit this line. ASTVarDeclId.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jmmCompiler.lexical;

public
class ASTVarDeclId extends SimpleNode {
  public ASTVarDeclId(int id) {
    super(id);
  }

  public ASTVarDeclId(Scanner p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed15d7c6119e8e82ba7f45ba7e06a2d3 (do not edit this line) */
