/* Generated By:JavaCC: Do not edit this line. ScannerTreeConstants.java Version 6.0_1 */
package jmmCompiler.lexical;

public interface ScannerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVOID = 2;
  public int JJTFIELDDECL = 3;
  public int JJTMETHODDECL = 4;
  public int JJTMETHODDECLARATOR = 5;
  public int JJTFORMALPARAMETERS = 6;
  public int JJTFORMALPARAMETER = 7;
  public int JJTCONSTRUCTORDECL = 8;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 9;
  public int JJTARRAYTYPE = 10;
  public int JJTPRIMITIVETYPE = 11;
  public int JJTRESULTTYPE = 12;
  public int JJTNAME = 13;
  public int JJTMODIFIERSTATIC = 14;
  public int JJTMODIFIER = 15;
  public int JJTBLOCK = 16;
  public int JJTINITIALIZEREXP = 17;
  public int JJTLOCALVARDECL = 18;
  public int JJTEMPTYSTATEMENT = 19;
  public int JJTIFSTATEMENT = 20;
  public int JJTWHILESTATEMENT = 21;
  public int JJTDOSTATEMENT = 22;
  public int JJTFORSTATEMENT = 23;
  public int JJTFORINIT = 24;
  public int JJTFORUPDATE = 25;
  public int JJTSTATEMENTEXPRESSIONLIST = 26;
  public int JJTFOREACHSTATEMENT = 27;
  public int JJTBREAKSTATEMENT = 28;
  public int JJTCONTINUESTATEMENT = 29;
  public int JJTRETURNSTATEMENT = 30;
  public int JJTEXPRESSION = 31;
  public int JJTOREXP = 32;
  public int JJTANDEXP = 33;
  public int JJTEQUALITYEXP = 34;
  public int JJTINSTANCEOFEXP = 35;
  public int JJTRELATIONALEXP = 36;
  public int JJTADDEXP = 37;
  public int JJTMULTIEXP = 38;
  public int JJTUNARYEXPRESSION = 39;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 40;
  public int JJTNOTEXPRESSION = 41;
  public int JJTCASTLOOKAHEAD = 42;
  public int JJTCASTEXPRESSION = 43;
  public int JJTPRIMARYEXPRESSION = 44;
  public int JJTPRIMARYPREFIX = 45;
  public int JJTPRIMARYSUFFIX = 46;
  public int JJTARRAYACCESS = 47;
  public int JJTLITERAL = 48;
  public int JJTEQUEALOP = 49;
  public int JJTRELATIONOP = 50;
  public int JJTADDOP = 51;
  public int JJTMULTIPLYOP = 52;
  public int JJTARGUMENTS = 53;
  public int JJTALLOCATIONEXPRESSION = 54;
  public int JJTARRAYDIMSANDINITS = 55;


  public String[] jjtNodeName = {
    "Start",
    "ClassDeclaration",
    "void",
    "FieldDecl",
    "MethodDecl",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDecl",
    "ExplicitConstructorInvocation",
    "ArrayType",
    "PrimitiveType",
    "ResultType",
    "Name",
    "ModifierStatic",
    "Modifier",
    "Block",
    "InitializerExp",
    "LocalVarDecl",
    "EmptyStatement",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForInit",
    "ForUpdate",
    "StatementExpressionList",
    "ForeachStatement",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "Expression",
    "OrExp",
    "AndExp",
    "EqualityExp",
    "InstanceOfExp",
    "RelationalExp",
    "AddExp",
    "MultiExp",
    "UnaryExpression",
    "UnaryExpressionNotPlusMinus",
    "NotExpression",
    "CastLookahead",
    "CastExpression",
    "PrimaryExpression",
    "PrimaryPrefix",
    "PrimarySuffix",
    "ArrayAccess",
    "Literal",
    "EquealOp",
    "RelationOp",
    "AddOp",
    "MultiplyOp",
    "Arguments",
    "AllocationExpression",
    "ArrayDimsAndInits",
  };
}
/* JavaCC - OriginalChecksum=2154867abbf43754a96000f1f639269b (do not edit this line) */
