/* Generated By:JavaCC: Do not edit this line. ScannerTreeConstants.java Version 6.0_1 */
package jmmCompiler.lexical;

public interface ScannerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTCLASSBODYDECL = 3;
  public int JJTFIELDDECL = 4;
  public int JJTMETHODDECL = 5;
  public int JJTMETHODDECLARATOR = 6;
  public int JJTFORMALPARAMETERS = 7;
  public int JJTFORMALPARAMETER = 8;
  public int JJTCONSTRUCTORDECL = 9;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 10;
  public int JJTARRAYTYPE = 11;
  public int JJTPRIMITIVETYPE = 12;
  public int JJTRESULTTYPE = 13;
  public int JJTNAME = 14;
  public int JJTMODIFIERSTATIC = 15;
  public int JJTMODIFIER = 16;
  public int JJTBLOCK = 17;
  public int JJTINITIALIZEREXP = 18;
  public int JJTLOCALVARDECL = 19;
  public int JJTEMPTYSTATEMENT = 20;
  public int JJTIFSTATEMENT = 21;
  public int JJTWHILESTATEMENT = 22;
  public int JJTDOSTATEMENT = 23;
  public int JJTFORSTATEMENT = 24;
  public int JJTFORINIT = 25;
  public int JJTFORUPDATE = 26;
  public int JJTSTATEMENTEXPRESSIONLIST = 27;
  public int JJTFOREACHSTATEMENT = 28;
  public int JJTBREAKSTATEMENT = 29;
  public int JJTCONTINUESTATEMENT = 30;
  public int JJTRETURNSTATEMENT = 31;
  public int JJTASSIGNEXP = 32;
  public int JJTOREXP = 33;
  public int JJTANDEXP = 34;
  public int JJTEQUALITYEXP = 35;
  public int JJTINSTANCEOFEXP = 36;
  public int JJTRELATIONALEXP = 37;
  public int JJTADDEXP = 38;
  public int JJTMULTIEXP = 39;
  public int JJTUNARYEXPRESSION = 40;
  public int JJTNOTEXPRESSION = 41;
  public int JJTCASTLOOKAHEAD = 42;
  public int JJTCASTEXPRESSION = 43;
  public int JJTPRIMARYEXPRESSION = 44;
  public int JJTARRAYACCESS = 45;
  public int JJTLITERAL = 46;
  public int JJTARGUMENTS = 47;
  public int JJTALLOCATIONEXPRESSION = 48;
  public int JJTARRAYDIMSANDINITS = 49;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "ClassDeclaration",
    "ClassBodyDecl",
    "FieldDecl",
    "MethodDecl",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDecl",
    "ExplicitConstructorInvocation",
    "ArrayType",
    "PrimitiveType",
    "ResultType",
    "Name",
    "ModifierStatic",
    "Modifier",
    "Block",
    "InitializerExp",
    "LocalVarDecl",
    "EmptyStatement",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForInit",
    "ForUpdate",
    "StatementExpressionList",
    "ForeachStatement",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "AssignExp",
    "OrExp",
    "AndExp",
    "EqualityExp",
    "InstanceOfExp",
    "RelationalExp",
    "AddExp",
    "MultiExp",
    "UnaryExpression",
    "NotExpression",
    "CastLookahead",
    "CastExpression",
    "PrimaryExpression",
    "ArrayAccess",
    "Literal",
    "Arguments",
    "AllocationExpression",
    "ArrayDimsAndInits",
  };
}
/* JavaCC - OriginalChecksum=796fe33dff75c2632ef5bb880b893cda (do not edit this line) */
